package main

import (
	"io/ioutil"
	"testing"

	"github.com/juliecoding/svg-cli/cli"
)

func TestNoFilters(t *testing.T) {
    match :=
`<?xml version="1.0"?>
<!-- Generated by SVGo -->
<svg width="1024" height="1073"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>
</defs>
<image x="0" y="0" width="1024" height="1073" xlink:href="/Users/tinaturner/go/src/github.com/juliecoding/svg-cli/test/testImg.jpeg" />
</svg>`
	cli.Run([]string{"-in=testImg.jpeg", "-out=out/TestNoFilters.svg"})
    output, err := ioutil.ReadFile("out/TestNoFilters.svg")
    if string(output) != match || err != nil {
        t.Fatal("Error creating SVG without filters")
    }
}
